//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.10.13 at 02:43:05 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://bean.jd02_09.yaroshchuk.it.by/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package by.it.yaroshchuk.jd02_09.bean;
