//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.13 at 02:42:33 PM MSK 
//


package by.it.nesterovich.jd02_09.beans;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Film complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Film">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Genre" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="YearOfIssue" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="Duration" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="Cinemas" type="{http://beans.jd02_09.nesterovich.it.by/}Cinemas"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Film", propOrder = {
    "name",
    "genre",
    "country",
    "yearOfIssue",
    "duration",
    "cinemas"
})
public class Film {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Genre", required = true)
    protected String genre;
    @XmlElement(name = "Country", required = true)
    protected String country;
    @XmlElement(name = "YearOfIssue", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger yearOfIssue;
    @XmlElement(name = "Duration", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger duration;
    @XmlElement(name = "Cinemas", required = true)
    protected Cinemas cinemas;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the genre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenre() {
        return genre;
    }

    /**
     * Sets the value of the genre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenre(String value) {
        this.genre = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the yearOfIssue property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getYearOfIssue() {
        return yearOfIssue;
    }

    /**
     * Sets the value of the yearOfIssue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setYearOfIssue(BigInteger value) {
        this.yearOfIssue = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDuration(BigInteger value) {
        this.duration = value;
    }

    /**
     * Gets the value of the cinemas property.
     * 
     * @return
     *     possible object is
     *     {@link Cinemas }
     *     
     */
    public Cinemas getCinemas() {
        return cinemas;
    }

    /**
     * Sets the value of the cinemas property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cinemas }
     *     
     */
    public void setCinemas(Cinemas value) {
        this.cinemas = value;
    }

    @Override
    public String toString() {
        return "\nFilm{" +
                "\nname='" + name + '\'' +
                ",\n genre='" + genre + '\'' +
                ",\n country='" + country + '\'' +
                ",\n yearOfIssue=" + yearOfIssue +
                ",\n duration=" + duration +
                ",\n cinemas=" + cinemas +
                "\n}";
    }
}
