//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.10.17 at 09:58:07 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://beans.jd02_09.jd02.voinilo.it.by/xml/Persons", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package by.it.voinilo.jd02.jd02_09.beans.xml.persons;
