//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.10.16 at 09:32:02 AM MSK 
//


package by.it.litvin.jd02_09.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Temporary complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Temporary"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Support" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="SemiSupport" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="HardLane" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Mid" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="EasyLane" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Temporary", propOrder = {
    "support",
    "semiSupport",
    "hardLane",
    "mid",
    "easyLane"
})
public class Temporary {

    @XmlElement(name = "Support", required = true)
    protected String support;
    @XmlElement(name = "SemiSupport", required = true)
    protected String semiSupport;
    @XmlElement(name = "HardLane", required = true)
    protected String hardLane;
    @XmlElement(name = "Mid", required = true)
    protected String mid;
    @XmlElement(name = "EasyLane", required = true)
    protected String easyLane;

    /**
     * Gets the value of the support property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupport() {
        return support;
    }

    /**
     * Sets the value of the support property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupport(String value) {
        this.support = value;
    }

    /**
     * Gets the value of the semiSupport property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSemiSupport() {
        return semiSupport;
    }

    /**
     * Sets the value of the semiSupport property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSemiSupport(String value) {
        this.semiSupport = value;
    }

    /**
     * Gets the value of the hardLane property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHardLane() {
        return hardLane;
    }

    /**
     * Sets the value of the hardLane property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHardLane(String value) {
        this.hardLane = value;
    }

    /**
     * Gets the value of the mid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMid() {
        return mid;
    }

    /**
     * Sets the value of the mid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMid(String value) {
        this.mid = value;
    }

    /**
     * Gets the value of the easyLane property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEasyLane() {
        return easyLane;
    }

    /**
     * Sets the value of the easyLane property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEasyLane(String value) {
        this.easyLane = value;
    }

}
