//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.14 at 12:13:16 PM MSK 
//


package by.it.basumatarau.jd02_09.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Venue complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Venue">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TypeTags" type="{http://beans.jd02_09.basumatarau.it.by/}TypeTags"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Place" type="{http://beans.jd02_09.basumatarau.it.by/}Place"/>
 *         &lt;element name="OpeningHours" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OpeningDates" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ParticipationFee" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Venue", propOrder = {
    "name",
    "typeTags",
    "description",
    "place",
    "openingHours",
    "openingDates",
    "participationFee"
})
public class Venue {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "TypeTags", required = true)
    protected TypeTags typeTags;
    @XmlElement(name = "Description", required = true)
    protected String description;
    @XmlElement(name = "Place", required = true)
    protected Place place;
    @XmlElement(name = "OpeningHours", required = true)
    protected String openingHours;
    @XmlElement(name = "OpeningDates", required = true)
    protected String openingDates;
    @XmlElement(name = "ParticipationFee", required = true)
    protected String participationFee;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the typeTags property.
     * 
     * @return
     *     possible object is
     *     {@link TypeTags }
     *     
     */
    public TypeTags getTypeTags() {
        return typeTags;
    }

    /**
     * Sets the value of the typeTags property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeTags }
     *     
     */
    public void setTypeTags(TypeTags value) {
        this.typeTags = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the place property.
     * 
     * @return
     *     possible object is
     *     {@link Place }
     *     
     */
    public Place getPlace() {
        return place;
    }

    /**
     * Sets the value of the place property.
     * 
     * @param value
     *     allowed object is
     *     {@link Place }
     *     
     */
    public void setPlace(Place value) {
        this.place = value;
    }

    /**
     * Gets the value of the openingHours property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpeningHours() {
        return openingHours;
    }

    /**
     * Sets the value of the openingHours property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpeningHours(String value) {
        this.openingHours = value;
    }

    /**
     * Gets the value of the openingDates property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpeningDates() {
        return openingDates;
    }

    /**
     * Sets the value of the openingDates property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpeningDates(String value) {
        this.openingDates = value;
    }

    /**
     * Gets the value of the participationFee property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParticipationFee() {
        return participationFee;
    }

    /**
     * Sets the value of the participationFee property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParticipationFee(String value) {
        this.participationFee = value;
    }

    @Override
    public String toString() {
        String result ="";
        result+="name"+name+'\n'+
                "typeTags: "+typeTags+
                "description"+description+'\n'+
                "place"+place+
                "openingHours"+openingHours+'\n'+
                "openingDates"+openingDates+'\n'+
                "participationFee"+participationFee+'\n';
        return result;
    }
}
