//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.15 at 06:40:31 PM MSK 
//


package by.it.galushka.jd02_09.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Lightweight" type="{http://beans.jd02_09.galushka.it.by/}Lightweight"/>
 *         &lt;element name="Middleweight" type="{http://beans.jd02_09.galushka.it.by/}Middleweight"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "lightweight",
    "middleweight"
})
@XmlRootElement(name = "Fighters")
public class Fighters {

    @XmlElement(name = "Lightweight", required = true)
    protected Lightweight lightweight;
    @XmlElement(name = "Middleweight", required = true)
    protected Middleweight middleweight;

    /**
     * Gets the value of the lightweight property.
     * 
     * @return
     *     possible object is
     *     {@link Lightweight }
     *     
     */
    public Lightweight getLightweight() {
        return lightweight;
    }

    /**
     * Sets the value of the lightweight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Lightweight }
     *     
     */
    public void setLightweight(Lightweight value) {
        this.lightweight = value;
    }

    /**
     * Gets the value of the middleweight property.
     * 
     * @return
     *     possible object is
     *     {@link Middleweight }
     *     
     */
    public Middleweight getMiddleweight() {
        return middleweight;
    }

    /**
     * Sets the value of the middleweight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Middleweight }
     *     
     */
    public void setMiddleweight(Middleweight value) {
        this.middleweight = value;
    }

}
