//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.15 at 06:40:31 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://beans.jd02_09.galushka.it.by/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package by.it.galushka.jd02_09.beans;
