//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.15 at 06:40:31 PM MSK 
//


package by.it.galushka.jd02_09.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Record complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Record">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Win" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Lose" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Draw" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Record", propOrder = {
    "win",
    "lose",
    "draw"
})
public class Record {

    @XmlElement(name = "Win")
    protected int win;
    @XmlElement(name = "Lose")
    protected int lose;
    @XmlElement(name = "Draw")
    protected int draw;

    /**
     * Gets the value of the win property.
     * 
     */
    public int getWin() {
        return win;
    }

    /**
     * Sets the value of the win property.
     * 
     */
    public void setWin(int value) {
        this.win = value;
    }

    /**
     * Gets the value of the lose property.
     * 
     */
    public int getLose() {
        return lose;
    }

    /**
     * Sets the value of the lose property.
     * 
     */
    public void setLose(int value) {
        this.lose = value;
    }

    /**
     * Gets the value of the draw property.
     * 
     */
    public int getDraw() {
        return draw;
    }

    /**
     * Sets the value of the draw property.
     * 
     */
    public void setDraw(int value) {
        this.draw = value;
    }

}
