//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.10.16 at 01:01:25 AM MSK 
//


package by.it.bindyuk.jd02_09.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for transportType complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="transportType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="from" type="{http://beans.jd02_09.bindyuk.it.by/}from"/&gt;
 *         &lt;element name="pointTo" type="{http://beans.jd02_09.bindyuk.it.by/}pointTo"/&gt;
 *         &lt;element name="date" type="{http://beans.jd02_09.bindyuk.it.by/}date"/&gt;
 *         &lt;element name="typeTicket" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "transportType", propOrder = {
    "from",
    "pointTo",
    "date",
    "typeTicket",
    "price"
})
public class TransportType {

    @XmlElement(required = true)
    protected From from;
    @XmlElement(required = true)
    protected PointTo pointTo;
    @XmlElement(required = true)
    protected Date date;
    @XmlElement(required = true)
    protected String typeTicket;
    @XmlElement(required = true)
    protected String price;
    @XmlAttribute(name = "type", required = true)
    protected String type;

    /**
     * Gets the value of the from property.
     * 
     * @return
     *     possible object is
     *     {@link From }
     *     
     */
    public From getFrom() {
        return from;
    }

    /**
     * Sets the value of the from property.
     * 
     * @param value
     *     allowed object is
     *     {@link From }
     *     
     */
    public void setFrom(From value) {
        this.from = value;
    }

    /**
     * Gets the value of the pointTo property.
     * 
     * @return
     *     possible object is
     *     {@link PointTo }
     *     
     */
    public PointTo getPointTo() {
        return pointTo;
    }

    /**
     * Sets the value of the pointTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PointTo }
     *     
     */
    public void setPointTo(PointTo value) {
        this.pointTo = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link Date }
     *     
     */
    public Date getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date }
     *     
     */
    public void setDate(Date value) {
        this.date = value;
    }

    /**
     * Gets the value of the typeTicket property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeTicket() {
        return typeTicket;
    }

    /**
     * Sets the value of the typeTicket property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeTicket(String value) {
        this.typeTicket = value;
    }

    /**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrice(String value) {
        this.price = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
